const questionBank = [
    {
      id: 1,
      category: 'ATA 18',
      question: 'Which type of balancing ensures that components are balanced around their center of gravity when not moving?',
      options: { a: 'Dynamic Balancing', b: 'Static Balancing', c: 'Passive Vibration Control' },
      correct: 'b',
    },
    {
      id: 2,
      category: 'ATA 18',
      question: 'What is the role of the Active Vibration Control (AVC) system in the S-92 helicopter?',
      options: { a: 'Reducing rotor track imbalance', b: 'Mitigating airframe vibrations', c: 'Adjusting blade track and balance' },
      correct: 'b',
    },
    {
      id: 3,
      category: 'ATA 18',
      question: 'What is the most likely cause of rotor vibration in the S-92 related to the blades?',
      options: { a: 'Static imbalance', b: 'Dynamic imbalance', c: 'Faulty AVC components' },
      correct: 'b',
    },
    {
      id: 4,
      category: 'ATA 18',
      question: 'How is dynamic balancing of the main rotor blades in the S-92 achieved?',
      options: { a: 'Adjusting pitch change rods', b: 'Using balance weights at the hub', c: 'Applying vibration sensors' },
      correct: 'b',
    },
    {
      id: 5,
      category: 'ATA 18',
      question: 'What is the purpose of the blade tracker in the HUMS system?',
      options: { a: 'Monitoring tail rotor balance', b: 'Providing blade track and lead/lag data', c: 'Adjusting main rotor pitch' },
      correct: 'b',
    },
    {
        id: 6,
        category: 'ATA 18',
        question: 'How is dynamic balancing of the tail rotor achieved in the S-92?',
        options: { a: 'Adjusting weights in the leading edge', b: 'Using balance weights at the hub', c: 'Applying reflective tape on blades' },
        correct: 'b',
    },
    {
        id: 7,
        category: 'ATA 18',
        question: 'What is the purpose of the HUMS Main Processing Unit (MPU)?',
        options: { a: 'Balancing main rotor blades', b: 'Collecting and analyzing sensor data', c: 'Controlling airframe vibrations' },
        correct: 'b',
    },
    {
        id: 8,
        category: 'ATA 18',
        question: 'Which material is NOT used for making set screws for balancing the High-Speed Shaft flange?',
        options: { a: 'Steel', b: 'Titanium', c: 'Brass' },
        correct: 'c',
    },
    {
        id: 9,
        category: 'ATA 18',
        question: 'When is the active mode of the Blade Tracker used?',
        options: { a: 'During daylight', b: 'In low light levels or at night', c: 'During static balancing' },
        correct: 'b',
    },


    {
        id: 10,
        category: 'ATA 18',
        question: 'How many force generators are typically installed in newer aircraft configurations?',
        options: { a: '3', b: '6', c: '10' },
        correct: 'b',
    },
    {
        id: 11,
        category: 'ATA 18',
        question: 'Where is the AVCC located in the aircraft?',
        options: { a: 'Nose wheel well', b: 'Bottom of the RH avionics cabinet', c: 'Forward cabin floor' },
        correct: 'b',
    },
    {
        id: 12,
        category: 'ATA 18',
        question: 'How is EU #1 powered?',
        options: { a: 'DC power supply', b: 'AC power from 1 AC bus', c: 'AC power from 2 AC bus' },
        correct: 'c',
    },
    {
        id: 13,
        category: 'ATA 18',
        question: 'How many airframe accelerometers are used in the AVC system?',
        options: { a: '3', b: '6', c: '10' },
        correct: 'c',
    },
    {
        id: 14,
        category: 'ATA 18',
        question: 'What caution will be displayed if one or more Force Generators or four accelerometers fail?',
        options: { a: 'AVC DEGRADED', b: 'AVC FAIL', c: 'IBIT FAIL' },
        correct: 'a',
    },
    {
        id: 15,
        category: 'ATA 18',
        question: 'According to the MEL, is the AVC system essential for flight?',
        options: { a: 'Yes', b: 'No', c: 'Only in certain conditions' },
        correct: 'b',
    },
    {
        id: 16,
        category: 'ATA 18',
        question: 'Where should personnel be during the IBIT test?',
        options: { a: 'In the cockpit', b: 'In the avionic compartment', c: 'Outside the aircraft' },
        correct: 'c',
    },
    {
        id: 17,
        category: 'ATA 18',
        question: 'How is the IBIT test initiated?',
        options: { a: 'By turning off the VIB CTRL switch', b: 'By pressing the IBIT soft-key on the MFD screen', c: 'By disconnecting the force generators' },
        correct: 'b',
    },
    {
        id: 18,
        category: 'ATA 18',
        question: 'What caution is displayed if both AC generators fail or if the NR signal is lost?',
        options: { a: 'AVC DEGRADED', b: 'AVC FAIL', c: 'IBIT FAIL' },
        correct: 'b',
    },
    {
        id: 19,
        category: 'ATA 18',
        question: 'What happens if the IBIT test fails?',
        options: { a: 'The AVC system resets automatically', b: 'Maintenance status will be displayed', c: 'The airframe vibration level becomes noticeably smoother' },
        correct: 'b',
    },
    {
        id: 20,
        category: 'ATA 18',
        question: 'When will AVC FAIL Caution display be suppressed ',
        options: { a: 'less than 95% NR and WOW', b: 'In Flight', c: 'During power up' },
        correct: 'a',
    },
    {
        id: 21,
        category: 'ATA 34',
        question: 'What is the frequency range for VOR/ILS tuning?',
        options: { a: '108.00 to 112.00 MHz', b: '112.00 to 117.95 MHz', c: '108.00 to 117.95 MHz' },
        correct: 'c',
      },
      {
        id: 22,
        category: 'ATA 34',
        question: 'How are VOR frequencies selected within the range of 108.00 to 112.00 MHz?',
        options: { a: 'When the digit to the right of the decimal is an even number', b: 'When the digit to the right of the decimal is an odd number', c: 'All frequencies in this range are VOR frequencies' },
        correct: 'a',
      },
      {
        id: 23,
        category: 'ATA 34',
        question: 'What is the default frequency for ILS within the range of 108.00 to 112.00 MHz?',
        options: { a: '108.65', b: '109.50', c: '110.15' },
        correct: 'c',
      },
      {
        id: 24,
        category: 'ATA 34',
        question: 'Where is the Marker Beacon antenna located?',
        options: { a: 'Under the fuselage, level with the main entrance door', b: 'Below the co-pilot’s seat', c: 'In the nose compartment' },
        correct: 'b',
      },
      {
        id: 25,
        category: 'ATA 34',
        question: 'How are VOR/LOC and VHF 2 antennas connected?',
        options: { a: 'Through a coupler in the seat well under the co-pilot’s seat', b: 'Through a coupler below the floor of the forward Cabin area', c: 'They are not connected' },
        correct: 'b',
      },
      {
        id: 26,
        category: 'ATA 34',
        question: 'How is VOR information displayed on the MFDs controlled?',
        options: { a: 'Through the Display Control Panel (DCP)', b: 'Via the Remote Instrument Controller (RIC)', c: 'Automatically on the NAV display' },
        correct: 'a',
      },
      {
        id: 27,
        category: 'ATA 34',
        question: 'What does the white arrow controlled by the RIC represent?',
        options: { a: 'Glideslope indication', b: 'Marker Beacon indication', c: 'VOR radial selection' },
        correct: 'c',
      },
      {
        id: 28,
        category: 'ATA 34',
        question: 'In VOR Deviations, how is the lateral deviation bar oriented when the beacon is to the left of the selected radial?',
        options: { a: 'To the right', b: 'Centered', c: 'To the left' },
        correct: 'c',
      },
      {
        id: 29,
        category: 'ATA 34',
        question: 'What color is used to signify VOR or FMS deviation in the Lateral Deviation Bar?',
        options: { a: 'Magenta', b: 'Blue', c: 'Yellow' },
        correct: 'a',
      },
      {
        id: 30,
        category: 'ATA 34',
        question: 'What does a yellow text label indicate when the off-side VOR is selected as the active source of navigation?',
        options: { a: 'Signal weakness', b: 'System failure', c: 'Offside selection' },
        correct: 'c',
      },
      {
        id: 31,
        category: 'ATA 34',
        question: 'How is a failure of a VOR or ILS system displayed on the MFD?',
        options: { a: 'In green', b: 'In yellow', c: 'In red' },
        correct: 'c',
      },
      {
        id: 32,
        category: 'ATA 34',
        question: 'During an ILS approach, what does a full-scale lateral indication result in?',
        options: { a: 'Yellow diamond', b: 'Magenta diamond', c: 'White arrow' },
        correct: 'b',
      },
      {
        id: 33,
        category: 'ATA 34',
        question: 'Where is the DME Receiver/Transmitter located?',
        options: { a: 'Under the fuselage', b: 'In the left Avionics Rack', c: 'In the nose compartment' },
        correct: 'b',
      },
      {
        id: 34,
        category: 'ATA 34',
        question: 'How many channels does the scanning DME receiver have in one unit?',
        options: { a: '1', b: '2', c: '3' },
        correct: 'c',
      },
      {
        id: 35,
        category: 'ATA 34',
        question: 'What is Channel 3 used for in the scanning DME receiver?',
        options: { a: 'Auto-tune from FMS', b: 'Range calculation for VOR 2', c: 'Range calculation for ILS 2' },
        correct: 'a',
      },
      {
        id: 36,
        category: 'ATA 34',
        question: 'Where is the DME antenna located?',
        options: { a: 'Under the co-pilot’s seat', b: 'Under the aircraft on the left', c: 'In the nose compartment' },
        correct: 'b',
      },
      {
        id: 37,
        category: 'ATA 34',
        question: 'How is the DME frequency tuned?',
        options: { a: 'Independently on the DME Main Page', b: 'Paired with the NAV frequencies', c: 'Through the Display Control Panel (DCP)' },
        correct: 'b',
      },
      {
        id: 38,
        category: 'ATA 34',
        question: 'What does a yellow H next to the VOR frequency on the MFDs indicate?',
        options: { a: 'High signal strength', b: 'DME Hold function activated', c: 'Health issue with avionics' },
        correct: 'b',
      },
      {
        id: 39,
        category: 'ATA 34',
        question: 'How is DME Hold selected?',
        options: { a: 'Automatically', b: 'Through the Remote Instrument Controller (RIC)', c: 'From the RTU' },
        correct: 'c',
      },
      {
        id: 40,
        category: 'ATA 34',
        question: 'Where can you find the status of the DME system?',
        options: { a: 'NAV Main Page', b: 'HLTH >> AVIONICS Page 1', c: 'RTU Diagnostic Menu' },
        correct: 'b',
      },
      {
        id: 41,
        category: 'ATA 34',
        question: 'When testing the DME from RTU 1, what indicates a serviceable system?',
        options: { a: 'A yellow H on the MFDs', b: '100 NM under the VOR 1/ILS 1 blue indication', c: 'A green marker on the PFD' },
        correct: 'b',
      },
      {
        id: 42,
        category: 'ATA 34',
        question: 'How are VOR 1 and ILS 1 diagnostics accessed?',
        options: { a: 'From the NAV Main Page', b: 'RTU 1 Diagnostic Menu', c: 'HLTH >> AVIONICS Page 2' },
        correct: 'c',
      },
      {
        id: 43,
        category: 'ATA 34',
        question: 'What bus does VOR/ILS 1 use for power supply?',
        options: { a: 'No 1 DC Primary Bus', b: 'DC Essential Bus', c: 'AC Bus' },
        correct: 'a',
      },
      {
        id: 44,
        category: 'ATA 28',
        question: 'Where are the fuel tanks located in the aircraft?',
        options: { a: 'Sponsons', b: 'Fuselage', c: 'Tail' },
        correct: 'b',
      },
      {
        id: 45,
        category: 'ATA 28',
        question: 'What material are the fuel tank bladders made of?',
        options: { a: 'Aluminum', b: 'Nylon reinforced rubber', c: 'Carbon composite' },
        correct: 'b',
      },
     {
        id: 46,
        category: 'ATA 28',
        question: 'When Will PRIME PUMP FAIL Caution illuminate ?',
        options: { a: '< 5 psi', b: '< 55psi', c: 'Tank booster pump fail' },
        correct: 'a',
      },
      {
        id: 47,
        category: 'ATA 28',
        question: 'What triggers the FUEL 1/2 LOW CAUTION?',
        options: { a: '440 nautical miles', b: '98kg ± 20kg', c: 'Low-level fuel sensors' },
        correct: 'b',
      },
      {
        id: 48,
        category: 'ATA 28',
        question: 'What components can be accessed through the tank maintenance access panel?',
        options: { a: 'Engine mounts', b: 'Landing gear', c: 'Quantity probe, low-level fuel sensor, refuel/defuel valve' },
        correct: 'c',
      },
      {
        id: 49,
        category: 'ATA 28',
        question: 'What color is the main body of breakaway valves?',
        options: { a: 'Blue', b: 'Red', c: 'Yellow' },
        correct: 'b',
      },
      {
        id: 50,
        category: 'ATA 28',
        question: 'What is the maximum pressure allowed during pressure defuel?',
        options: { a: '55 psig', b: '-3 psig', c: '20 gpm' },
        correct: 'b',
      },
      {
        id: 51,
        category: 'ATA 28',
        question: 'Where is the aircraft pressure refuelled / defuelled from?',
        options: { a: 'Cockpit', b: 'LH sponson', c: 'Wingtip' },
        correct: 'b',
      },
      {
        id: 52,
        category: 'ATA 28',
        question: 'What does the Pressure Refuel Control Panel control?',
        options: { a: 'Engine thrust', b: 'Fuel tank temperature', c: 'Left and right sponson fuel delivery' },
        correct: 'c',
      },
      {
        id: 53,
        category: 'ATA 28',
        question: 'What is the purpose of the high-level shutoff valve in the fuel cell?',
        options: { a: 'Prevent fuel spills', b: 'Increase fuel flow', c: 'Maintain atmospheric pressure' },
        correct: 'a',
      },
      {
        id: 54,
        category: 'ATA 28',
        question: 'What is the purpose of the Auxiliary Tank - Fuel Management Panel?',
        options: { a: 'Engine control', b: 'Fuel quantity measurement', c: 'Aircraft navigation' },
        correct: 'b',
      },
      {
        id: 55,
        category: 'ATA 28',
        question: 'How much usable fuel does each Internal Auxiliary Fuel System (IAFS) tank hold?',
        options: { a: '210 USG', b: '382 gallons', c: '440 nautical miles' },
        correct: 'a',
      },
      {
        id: 56,
        category: 'ATA 28',
        question: 'What is the maximum defuel pressure allowed for the IAFS?',
        options: { a: '55 psig', b: '-3 psig', c: '20 gpm' },
        correct: 'b',
      },
      {
        id: 57,
        category: 'ATA 28',
        question: 'Where is the fuel management panel located?',
        options: { a: 'Pressure refuel point', b: 'Cockpit central pedestal', c: 'Fuel bowser' },
        correct: 'b',
      },
      {
        id: 58,
        category: 'ATA 28',
        question: 'What is the function of the Pressure Refuel Control switches during refuelling?',
        options: { a: 'Stop refuelling', b: 'Increase fuel flow', c: 'Manage cockpit pressure' },
        correct: 'a',
      },
      {
        id: 59,
        category: 'ATA 28',
        question: 'How are the aux tanks refuelled during pressure refuel operations?',
        options: { a: 'Simultaneously with main tanks', b: 'After main tanks are full', c: 'Independently of main tanks' },
        correct: 'a',
      },
      {
        id: 60,
        category: 'ATA 28',
        question: 'What does the Internal Auxiliary Fuel System (IAFS) MODE SELECT switch control?',
        options: { a: 'Engine mode', b: 'Fuel transfer mode', c: 'Aircraft speed' },
        correct: 'b',
      },
      {
        id: 61,
        category: 'ATA 28',
        question: 'What is the purpose of the gravity refuel adapter?',
        options: { a: 'Stop fuel flow', b: 'Provide tank access for gravity filling', c: 'Connect to the APU' },
        correct: 'b',
      },
      {
        id: 62,
        category: 'ATA 28',
        question: 'What should be checked before attempting gravity refuelling?',
        options: { a: 'Fuel temperature', b: 'Fuel level through sight glass', c: 'Engine oil level' },
        correct: 'b',
      },
      {
        id: 63,
        category: 'ATA 28',
        question: 'Where are the sump drains located?',
        options: { a: 'Top of the fuel tank', b: 'Pressure refuel point', c: 'Centrally in the bottom of each tank' },
        correct: 'c',
      },
      {
        id: 64,
        category: 'ATA 28',
        question: 'What is the total fuel capacity (pressure Refuel)',
        options: { a: '5175lbs', b: '1000lbs', c: '7700lbs' },
        correct: 'a',
      }
      
      
    

  
    
    // Add more questions as needed
  ];
  